### ISSUE TITLE
ABCs aren't abstract!

### ISSUE THREAD

**Issue by barneygale** [barneygale/pathlib_abc#2]
It shouldn't be possible to directly instantiate `PurePathBase` or `PathBase`.

**Comment by barneygale** [comment]
Actually... the base classes in `io` can be directly instantiated. Arguable?

**Comment by merwok** [comment]
Only classes with not-overriden abstract methods can’t be instantiated IIRC.
Otherwise you’re free to instantiate an ABC and maybe do useful things with the instance!

**Comment by barneygale** [comment]
Thank you! Resolving this issue.
