### ISSUE TITLE
`functools.cache()` is only available in Python 3.9+

### ISSUE THREAD

**Issue by barneygale** [barneygale/pathlib_abc#9]
There's one instance of `functools.cache()` in the upstream `pathlib._abc` package. This must be replaced for compatibility with Python 3.8 in this package.

**Comment by AlexWaygood** [comment]
Hmm, can't you just use `functools.lru_cache(maxsize=None)`?

**Comment by AlexWaygood** [comment]
Oh, I think I see -- you want the code in this package to match the upstream CPython code exactly, so that it's easy to keep the backport in sync with the CPython `main` branch? So you'd have to change CPython `pathlib` so that it used `lru_cache(maxsize=None)`? Fair enough!

**Comment by barneygale** [comment]
Yeah, that's the idea. I'm not expecting it to match _exactly_ as there will be import differences for example, but I'd like to keep the differences to a minimum.
